name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Lint the source code
      - name: Lint the source code
        run: |
          make lint
          
      # Test with pytest
      - name: Test with pytest
        run: |
          make test
